# Generated by Django 6.0.2 on 2026-02-22 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField(blank=True, help_text='Description or content')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('source_name', models.CharField(db_index=True, max_length=200)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('bias_label', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('unclassified', 'Unclassified')], db_index=True, default='unclassified', max_length=20)),
                ('bias_score', models.FloatField(default=0.0, help_text='Bias score from -1 (left) to +1 (right). Default 0 = neutral.', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['bias_label', '-published_at'], name='news_articl_bias_la_22ed9b_idx'), models.Index(fields=['source_name', '-published_at'], name='news_articl_source__6ab419_idx')],
                'unique_together': {('title', 'source_name')},
            },
        ),
    ]
